var refreshInterval=null;(function(){"use strict";var formPayout=$("#f-eWallet-payout");if(formPayout.length){formPayout.on('submit',function(e){e.preventDefault();$.ajax({url:formPayout.attr('action'),data:formPayout.serialize(),type:'post',dataType:'json',success:function(response){if(response.message){block_form(formPayout,false);var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}
if(response.data){var data=response.data;var id_invoice=data.id_invoice;$("#deposito").hide();$("#depositar").hide();$("#qrcode").attr('src','data:image/png;base64, '+data.qrcode);$("#copiacola").html(data.copiacola);$("#valorexib").html(data.valor);$("#mostra_qrcode").removeClass('hidden');$("#mostra_qrcode").removeClass('hidden');$("#depCopiaCodigo").attr('onclick','copyToClipboard(this, "'+data.copiacola+'")');ts();conversion(id_invoice);}}});block_form(formPayout,true);});}
var formPayout2=$("#f-eWallet-payout2");if(formPayout2.length){formPayout2.on('submit',function(e){e.preventDefault();$.ajax({url:formPayout2.attr('action'),data:formPayout2.serialize(),type:'post',dataType:'json',success:function(response){if(response.message){block_form(formPayout2,false);var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}}});block_form(formPayout2,true);});}
var formTransfer=$("#f-eWallet-transfer");if(formTransfer.length){formTransfer.on('submit',function(e){e.preventDefault();$.ajax({url:formTransfer.attr('action'),data:formTransfer.serialize(),type:'post',dataType:'json',success:function(response){if(response.message){block_form(formTransfer,false);var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}}});block_form(formTransfer,true);});}
var formSpecial=$("#f-eWallet-special");if(formSpecial.length){$("#search-invoice",formSpecial).click(function(){$.ajax({url:make_url('panel.invoices.info'),data:{id:$('#invoice_id',formSpecial).val()},type:'post',dataType:'json',success:function(response){if(response.message){var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}
if(response.data){var data=response.data;$("#username",formSpecial).val(data.username);$("#total",formSpecial).val(data.total);$("#pay-invoice",formSpecial).removeAttr('disabled');$('#pay-invoice').prop("disabled",false);}}});});formSpecial.on('submit',function(e){e.preventDefault();$.ajax({url:formSpecial.attr('action'),data:formSpecial.serialize(),type:'post',dataType:'json',success:function(response){if(response.message){block_form(formSpecial,false);var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}}});block_form(formSpecial,true);});}
var formSpecial2=$("#f-eWallet-special2");if(formSpecial2.length){$("#search-invoice",formSpecial2).click(function(){$.ajax({url:make_url('panel.invoices.info2'),data:{id:$('#invoice_id',formSpecial2).val()},type:'post',dataType:'json',success:function(response){if(response.message){var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}
if(response.data){var data=response.data;$("#username",formSpecial2).val(data.username);$("#total",formSpecial2).val(data.total);$("#pay-invoice",formSpecial2).removeAttr('disabled');}}});});formSpecial2.on('submit',function(e){e.preventDefault();$.ajax({url:formSpecial2.attr('action'),data:formSpecial2.serialize(),type:'post',dataType:'json',success:function(response){if(response.message){block_form(formSpecial2,false);var type=response.success?'success':'error';toastr[type](response.message);}
if(response.redirect){var redirect=setTimeout(function(){window.location.href=make_url(response.redirect);clearTimeout(redirect);},1500)}}});block_form(formSpecial2,true);});}})();function checkGold()
{$.ajax({url:'./balance',data:"",dataType:'json',success:function(response){if(response[0]=='true'){valor=parseFloat(response[1]);valorFormatado=valor.toLocaleString('pt-BR',{minimumFractionDigits:2});if(player_saldo!=valor){$('div.cashbox').find('b.saldo').html(valorFormatado);player_saldo=valor;clearInterval(refreshInterval);}}else{clearInterval(refreshInterval);}},error:function(xhr,status){clearInterval(refreshInterval);}});}
function conversion(id){$.post("/panel/sync",{id:id},function(data){let status=data;if(status=='paid'){location.href="/panel/home?msg=depositsuccess"}else if(status=='pending'||status=='expired'){setTimeout('conversion('+id+')',5000);}});}
function ts(){var tempoEmMinutos=10;var expiracao=new Date(new Date().getTime()+tempoEmMinutos*60000);console.log(expiracao);contador=window.setInterval(function(){faltam=expiracao-new Date();if(faltam<=0){window.clearInerval(contador);}
minutos=Math.floor(faltam/60000);segundos=faltam%60000;tempoRestante=`${minutos}:${segundos.toString().substring(0,2)}`;document.getElementById('tempo').innerText=tempoRestante;console.log(tempoRestante);},1000);}